routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/home', function (){
   return ('HOla');
});*/
Route::get('/usuarios', 'UserController@index')
    ->name('users.index');
Route::get('/usuarios/{user}', 'UserController@show')
    ->where('user', '[0-9]+')
    ->name('users.show');
Route::get('/usuarios/nuevo', 'UserController@create')->name('users.create');
Route::post('/usuarios', 'UserController@store');
Route::get('/usuarios/{user}/editar', 'UserController@edit')->name('users.edit');
Route::put('/usuarios/{user}', 'UserController@update');
Route::delete('/usuarios/{user}', 'UserController@destroy')->name('users.destroy');


Route::get('/', function () {
    return view('welcome');
});
Route::resource('organizadors','OrganizadorController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Organizador.php
<?php

namespace App;
use Laravel\Passport\HasApiTokens;
use App\Evento;
use App\Comentario;
use App\SocialAccount;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Organizador extends Model
{
    protected $fillable = [
        'name', 'email','password','cedula','genero', 'telefono', 'descripcion_perfil',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','cedula'
    ];
    public function socialAccounts(){
        return $this->hasMany(SocialAccount::class);
    }

    public function eventos(){
        return $this->hasMany(Evento::class, 'id_guia');
    }
    public function comentarios(){
        return $this->hasMany(Comentario::class, 'id_guia');
    }
}

resources/views/organizadors/create.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New organizador</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('organizadors.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' => 'organizadors.store','method'=>'POST')) !!}
         @include('organizadors.form')
    {!! Form::close() !!}
@endsection

resources/views/organizadors/edit.blade.php
@extends('layouts.default')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit organizador</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('organizadors.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::model($organizador, ['method' => 'PATCH','route' => ['organizadors.update', $organizador->id]]) !!}
        @include('organizadors.form')
    {!! Form::close() !!}
@endsection

resources/views/organizadors/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::email('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/organizadors/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>organizadors CRUD</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('organizadors.create') }}"> Create New organizador</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Email</th>
            <th width="280px">Operation</th>
        </tr>
    @foreach ($organizadors as $organizador)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $organizador->name}}</td>
        <td>{{ $organizador->email}}</td>
        <td>
            <a class="btn btn-info" href="{{ route('organizadors.show',$organizador->id) }}">Show</a>
            <a class="btn btn-primary" href="{{ route('organizadors.edit',$organizador->id) }}">Edit</a>
            {!! Form::open(['method' => 'DELETE','route' => ['organizadors.destroy', $organizador->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </table>
    {!! $organizadors->render() !!}
@endsection

resources/views/organizadors/show.blade.php
@extends('layouts.default')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show organizador</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('organizadors.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $organizador->name}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $organizador->email}}
            </div>
        </div>
    </div>
@endsection